#### To deploy the lambda function from a container image
#### Create the custom image using the below dockerfile
#### Then push the image to you Elastic Container Registry Repo 
#### The repo needs to be private, not public for it to be recognized by AWS Lambda 

# Python version
# https://gallery.ecr.aws/lambda/python
FROM public.ecr.aws/lambda/python:3.8
# Dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Code file plus configuration file
COPY lambda_function.py ./
COPY config.toml ./ 
COPY .env ./

# Command to execute when container starts
CMD ["lambda_function.lambda_handler"]